# Generated by Django 6.0.5 on 2026-09-08 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dificultad',
            },
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('criterio_obtencion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insignia',
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('mecanica', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'juego',
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('numero_letras', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'lista',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nivel',
            },
        ),
        migrations.CreateModel(
            name='TipoRanking',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_ranking',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pila', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='home.tipousuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_pila', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to=settings.AUTH_USER_MODEL)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='home.carrera')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='home.nivel')),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=100)),
                ('significado', models.CharField(max_length=100)),
                ('pronunciacion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='palabras/imagenes/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='palabras/audios')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palabras', to='home.categoria')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palabras', to='home.nivel')),
            ],
            options={
                'db_table': 'palabra',
            },
        ),
        migrations.CreateModel(
            name='Practica_Sesion',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('duracion', models.DurationField()),
                ('porcentaje_aciertos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('puntos_obtenidos', models.PositiveIntegerField(default=0)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practicas', to='home.juego')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practicas', to='home.lista')),
            ],
            options={
                'db_table': 'practica_sesion',
            },
        ),
        migrations.CreateModel(
            name='Intento_Palabra',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('acertado', models.BooleanField(default=False)),
                ('tiempo_respuesta', models.DurationField(blank=True, null=True)),
                ('numero_intentos', models.PositiveIntegerField(default=1)),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='home.palabra')),
                ('practica_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='home.practica_sesion')),
            ],
            options={
                'db_table': 'intento_palabra',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pila', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profesor',
            },
        ),
        migrations.AddField(
            model_name='lista',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas', to='home.profesor'),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('ciclo', models.CharField(max_length=50)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesores', to='home.profesor')),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('minimo', models.PositiveIntegerField()),
                ('maximo', models.PositiveIntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rangos', to='home.alumno')),
            ],
            options={
                'db_table': 'rango',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('tipo_reporte', models.CharField(max_length=100)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='home.profesor')),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.PositiveIntegerField()),
                ('periodo', models.CharField(max_length=100)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='home.alumno')),
                ('tipo_ranking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankings', to='home.tiporanking')),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
        migrations.CreateModel(
            name='Grupo_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_alumnos', to='home.alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_alumnos', to='home.grupo')),
            ],
            options={
                'db_table': 'grupo_alumno',
                'constraints': [models.UniqueConstraint(fields=('grupo', 'alumno'), name='unique_grupo_alumno')],
            },
        ),
        migrations.CreateModel(
            name='Alumno_Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to='home.alumno')),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='home.insignia')),
            ],
            options={
                'db_table': 'alumno_insignia',
                'constraints': [models.UniqueConstraint(fields=('alumno', 'insignia'), name='unique_alumno_insignia')],
            },
        ),
        migrations.CreateModel(
            name='Dificultad_Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='home.dificultad')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dificultades', to='home.juego')),
            ],
            options={
                'db_table': 'dificultad_juego',
                'constraints': [models.UniqueConstraint(fields=('juego', 'dificultad'), name='unique_juego_dificultad')],
            },
        ),
        migrations.CreateModel(
            name='Lista_Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_grupos', to='home.grupo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_grupos', to='home.lista')),
            ],
            options={
                'db_table': 'lista_grupo',
                'constraints': [models.UniqueConstraint(fields=('lista', 'grupo'), name='unique_lista_grupo')],
            },
        ),
        migrations.CreateModel(
            name='Lista_Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_palabras', to='home.lista')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_palabras', to='home.palabra')),
            ],
            options={
                'db_table': 'lista_palabra',
                'constraints': [models.UniqueConstraint(fields=('lista', 'palabra'), name='unique_lista_palabra')],
            },
        ),
        migrations.CreateModel(
            name='Alumno_Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='home.alumno')),
                ('practica_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='home.practica_sesion')),
            ],
            options={
                'db_table': 'alumno_practica',
                'constraints': [models.UniqueConstraint(fields=('alumno', 'practica_sesion'), name='unique_alumno_practica')],
            },
        ),
        migrations.CreateModel(
            name='Proceso_Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_aciertos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lista_desbloqueada', models.BooleanField(default=False)),
                ('fecha_completado', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_lista', to='home.alumno')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='home.lista')),
            ],
            options={
                'db_table': 'proceso_lista',
                'constraints': [models.UniqueConstraint(fields=('lista', 'alumno'), name='unique_proceso_lista')],
            },
        ),
    ]
