# Generated by Django 6.0.5 on 2026-09-14 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dificultad',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(db_column='fechaCreacion')),
                ('ciclo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('criterio_obtencion', models.CharField(db_column='crit_obtencion', max_length=50)),
            ],
            options={
                'db_table': 'insignia',
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('mecanica', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'juego',
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('numero_letras', models.IntegerField()),
            ],
            options={
                'db_table': 'lista',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nivel',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_pila', models.CharField(max_length=30)),
                ('apellidoPaterno', models.CharField(db_column='apellPaterno', max_length=30)),
                ('apellidoMaterno', models.CharField(db_column='apellMaterno', max_length=30)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('numero_telefono', models.CharField(db_column='telefono', max_length=20)),
                ('password', models.CharField(db_column='contraseña', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tipo_usuario', models.ForeignKey(db_column='tipo_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='home.tipousuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_pila', models.CharField(db_column='nombre_pila', max_length=30)),
                ('apellidoPaterno', models.CharField(db_column='apellPaterno', max_length=30)),
                ('apellidoMaterno', models.CharField(blank=True, db_column='apellMaterno', max_length=30, null=True)),
                ('usuario', models.OneToOneField(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_pila', models.CharField(db_column='nombrePila', max_length=30)),
                ('apellidoPaterno', models.CharField(db_column='apellPaterno', max_length=100)),
                ('apellidoMaterno', models.CharField(blank=True, db_column='apellMaterno', max_length=100, null=True)),
                ('usuario', models.OneToOneField(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to=settings.AUTH_USER_MODEL)),
                ('carrera', models.ForeignKey(db_column='carrera', on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='home.carrera')),
                ('nivel', models.ForeignKey(db_column='nivel', on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='home.nivel')),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='Grupo_Alumno',
            fields=[
                ('pk', models.CompositePrimaryKey('grupo', 'alumno', blank=True, editable=False, primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(db_column='alumno', on_delete=django.db.models.deletion.CASCADE, related_name='grupo_alumnos', to='home.alumno')),
                ('grupo', models.ForeignKey(db_column='grupo', on_delete=django.db.models.deletion.CASCADE, related_name='grupo_alumnos', to='home.grupo')),
            ],
            options={
                'db_table': 'grupo_alumno',
            },
        ),
        migrations.CreateModel(
            name='Alumno_Insignia',
            fields=[
                ('fecha_obtenida', models.DateField(blank=True, db_column='fecha_obtencion', null=True)),
                ('pk', models.CompositePrimaryKey('alumno', 'insignia', blank=True, editable=False, primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(db_column='alumno', on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to='home.alumno')),
                ('insignia', models.ForeignKey(db_column='insignia', on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='home.insignia')),
            ],
            options={
                'db_table': 'alumno_insignia',
            },
        ),
        migrations.CreateModel(
            name='Dificultad_Juego',
            fields=[
                ('pk', models.CompositePrimaryKey('juego', 'dificultad', blank=True, editable=False, primary_key=True, serialize=False)),
                ('dificultad', models.ForeignKey(db_column='dificultad', on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='home.dificultad')),
                ('juego', models.ForeignKey(db_column='juego', on_delete=django.db.models.deletion.CASCADE, related_name='dificultades', to='home.juego')),
            ],
            options={
                'db_table': 'dificultad_juego',
            },
        ),
        migrations.CreateModel(
            name='Lista_Grupo',
            fields=[
                ('pk', models.CompositePrimaryKey('lista', 'grupo', blank=True, editable=False, primary_key=True, serialize=False)),
                ('grupo', models.ForeignKey(db_column='grupo', on_delete=django.db.models.deletion.CASCADE, related_name='lista_grupos', to='home.grupo')),
                ('lista', models.ForeignKey(db_column='lista', on_delete=django.db.models.deletion.CASCADE, related_name='lista_grupos', to='home.lista')),
            ],
            options={
                'db_table': 'lista_grupo',
            },
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('significado', models.CharField(max_length=50)),
                ('pronunciacion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='palabras/imagenes/')),
                ('audio', models.FileField(upload_to='palabras/audios/')),
                ('categoria', models.ForeignKey(db_column='categoria', on_delete=django.db.models.deletion.PROTECT, related_name='palabras', to='home.categoria')),
                ('nivel', models.ForeignKey(db_column='nivel', on_delete=django.db.models.deletion.PROTECT, related_name='palabras', to='home.nivel')),
            ],
            options={
                'db_table': 'palabra',
            },
        ),
        migrations.CreateModel(
            name='Lista_Palabra',
            fields=[
                ('pk', models.CompositePrimaryKey('lista', 'palabra', blank=True, editable=False, primary_key=True, serialize=False)),
                ('lista', models.ForeignKey(db_column='lista', on_delete=django.db.models.deletion.CASCADE, related_name='lista_palabras', to='home.lista')),
                ('palabra', models.ForeignKey(db_column='palabra', on_delete=django.db.models.deletion.CASCADE, related_name='lista_palabras', to='home.palabra')),
            ],
            options={
                'db_table': 'lista_palabra',
            },
        ),
        migrations.CreateModel(
            name='Practica_Sesion',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('duracion', models.DurationField()),
                ('porcentaje_aciertos', models.FloatField(db_column='porcent_aciertos')),
                ('puntos_obtenidos', models.FloatField(db_column='puntos_obt')),
                ('juego', models.ForeignKey(db_column='juego', on_delete=django.db.models.deletion.PROTECT, related_name='practicas', to='home.juego')),
                ('lista', models.ForeignKey(db_column='lista', on_delete=django.db.models.deletion.PROTECT, related_name='practicas', to='home.lista')),
            ],
            options={
                'db_table': 'practica_sesion',
            },
        ),
        migrations.CreateModel(
            name='Intento_Palabra',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('acertado', models.IntegerField()),
                ('tiempo_respuesta', models.TimeField(blank=True, null=True)),
                ('numero_intentos', models.IntegerField()),
                ('palabra', models.ForeignKey(db_column='palabra', on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='home.palabra')),
                ('practica_sesion', models.ForeignKey(db_column='practica_sesion', on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='home.practica_sesion')),
            ],
            options={
                'db_table': 'intento_palabra',
            },
        ),
        migrations.CreateModel(
            name='Alumno_Practica',
            fields=[
                ('pk', models.CompositePrimaryKey('alumno', 'practica_sesion', blank=True, editable=False, primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(db_column='alumno', on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='home.alumno')),
                ('practica_sesion', models.ForeignKey(db_column='practica_sesion', on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='home.practica_sesion')),
            ],
            options={
                'db_table': 'alumno_practica',
            },
        ),
        migrations.CreateModel(
            name='Proceso_Lista',
            fields=[
                ('porcentaje_aciertos', models.FloatField(db_column='porcent_aciert')),
                ('lista_desbloqueada', models.CharField(max_length=10)),
                ('fecha_completado', models.DateField()),
                ('pk', models.CompositePrimaryKey('lista', 'alumno', blank=True, editable=False, primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(db_column='alumno', on_delete=django.db.models.deletion.CASCADE, related_name='procesos_lista', to='home.alumno')),
                ('lista', models.ForeignKey(db_column='lista', on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='home.lista')),
            ],
            options={
                'db_table': 'proceso_lista',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_pila', models.CharField(max_length=30)),
                ('apellidoPaterno', models.CharField(db_column='apellPaterno', max_length=100)),
                ('apellidoMaterno', models.CharField(blank=True, db_column='apellMaterno', max_length=100, null=True)),
                ('usuario', models.OneToOneField(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profesor',
            },
        ),
        migrations.AddField(
            model_name='lista',
            name='profesor',
            field=models.ForeignKey(db_column='profesor', on_delete=django.db.models.deletion.PROTECT, related_name='listas', to='home.profesor'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(db_column='profesor', on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='home.profesor'),
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('minimo', models.IntegerField()),
                ('maximo', models.IntegerField(blank=True, null=True)),
                ('alumno', models.ForeignKey(db_column='alumno', on_delete=django.db.models.deletion.PROTECT, related_name='rangos', to='home.alumno')),
            ],
            options={
                'db_table': 'rango',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('posicion', models.PositiveIntegerField()),
                ('periodo', models.CharField(max_length=20)),
                ('puntos', models.IntegerField()),
                ('alumno', models.ForeignKey(db_column='alumno', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='home.alumno')),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField(db_column='fecha_genera')),
                ('tipo_reporte', models.CharField(max_length=30)),
                ('profesor', models.ForeignKey(db_column='profesor', on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='home.profesor')),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='TipoRanking',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('ranking', models.ForeignKey(db_column='ranking', on_delete=django.db.models.deletion.PROTECT, related_name='tipos_ranking', to='home.ranking')),
            ],
            options={
                'db_table': 'tipo_ranking',
            },
        ),
    ]
