# Generated by Django 6.0.5 on 2026-09-09 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='clave',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidoMaterno',
            field=models.CharField(db_column='apellMaterno', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidoPaterno',
            field=models.CharField(db_column='apellPaterno', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_telefono',
            field=models.CharField(blank=True, db_column='telefono', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_column='contraseña', max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(db_column='tipo_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='home.tipousuario'),
        ),
    ]
